### ISSUE TITLE
Unable to import any files, locally or over web server

### ISSUE THREAD

**Issue by osoikuma** [juanj/KantanManga#41]
Sorry I'm new to GitHub. Made an account just for this. I downloaded the app, and I have jpeg files of the manga I want to ocr. I'm unable to select any of the images to import them. I could only kinda drag them, like I did in the image below, but that didn't do anything. ![image](https://user-images.githubusercontent.com/75455930/101101407-7b9a2c00-3596-11eb-80eb-c961eccd542a.jpeg) I tried using the web server, but I kept getting errors "Forbidden: Failed uploading "デスノート_1_005.jpg" to "/Manga/". There's no information on the App Store about compatible file types so I'm not sure what to do. I'm on iOS 14.2 btw.

**Comment by juanj** [comment]
Hey @osoikuma thank you for using the app!
Sorry for the lack of info about the file formats, is something I'm planning to add on the next version (#36).
Right now you can only import CBZ and CBR. These file formats are basically a ZIP of images or a RAR of images.
So to be able to import the images, first you need to create a zip file containing them.

**Comment by osoikuma** [comment]
Hey, thanks for helping me out. I changed the files to cbr format so it
works now.
I have a request though: Would you be able to make it possible to save
sentences for later? (For making Anki cards and stuff). I don’t have any
experience so I don’t know how hard something like that would be to code.
But I think something like that would be super useful. Especially because
you’re really the only free iOS ocr app out there lol. Regardless, thanks
for making this app. Hope it can develop into something great.

**Comment by juanj** [comment]
Yes! Part of the idea of the app was to be able to mine sentences for later adding to Anki. Is currently in my to-do list (#14). Right now I'm working on adding custom dictionaries support, but after that I may look in to it.

If you have any feedback don't hesitate to say it, this app is at an early stage and feedback is really valuable.
